# Generated by Django 4.2.30 on 2026-07-22 09:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('focus_hours', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('study_hours', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('momentum_score', models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('efficiency_index', models.FloatField(default=90.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analytics Telemetries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_a_user_id_db2b0f_idx')],
            },
        ),
    ]
