# Generated by Django 4.2.30 on 2026-07-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='analyticstelemetry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_telemetry'),
        ),
    ]
