# Generated by Django 4.2.30 on 2026-07-22 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('TASK_DUE', 'Task Due'), ('FOCUS_ALARM', 'Focus Alarm'), ('SECURITY_ALERT', 'Security Alert'), ('GOAL_MILESTONE', 'Goal Milestone')], db_index=True, default='TASK_DUE', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_27a12f_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_54751d_idx')],
            },
        ),
    ]
