import type { TaskItem, GoalItem, FocusSession, JournalEntry, SystemTelemetry } from '../types';

export const MOCK_USER = {
  id: 'usr-001-cyber',
  username: 'operator_alex',
  email: 'alex.vance@momentum.cyber',
  firstName: 'Alex',
  lastName: 'Vance',
  role: 'CEO' as const,
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
  createdAt: '2026-01-15T08:00:00Z',
};

export const MOCK_TELEMETRY: SystemTelemetry = {
  cpuUsage: 34.2,
  memoryUsage: 61.8,
  activeNodes: 128,
  syncLatencyMs: 14,
  uptimePercent: 99.98,
};

export const MOCK_TASKS: TaskItem[] = [
  {
    id: 'tsk-101',
    title: 'Deploy Zero-Trust Authentication Protocol',
    description: 'Implement JWT refresh rotation and biometric webauthn challenge.',
    status: 'IN_PROGRESS',
    priority: 'CRITICAL',
    category: 'Security Architecture',
    dueDate: '2026-07-25',
    estimatedMinutes: 180,
  },
  {
    id: 'tsk-102',
    title: 'Audit System Telemetry Metrics',
    description: 'Optimize TanStack Query cache invalidation strategy for low-latency nodes.',
    status: 'COMPLETED',
    priority: 'HIGH',
    category: 'Telemetry',
    dueDate: '2026-07-22',
    estimatedMinutes: 90,
  },
  {
    id: 'tsk-103',
    title: 'Refactor Glassmorphism Design Tokens',
    description: 'Update Tailwind neon blue & emerald glowing state tokens for dark/light themes.',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    category: 'UI/UX Design',
    dueDate: '2026-07-28',
    estimatedMinutes: 120,
  },
  {
    id: 'tsk-104',
    title: 'Configure PostgreSQL Connection Pool',
    description: 'Tune Django DB settings with persistent connections and index optimization.',
    status: 'TODO',
    priority: 'HIGH',
    category: 'Backend Pipeline',
    dueDate: '2026-07-30',
    estimatedMinutes: 150,
  },
  {
    id: 'tsk-105',
    title: 'Automate Daily Focus Session Analytics',
    description: 'Synthesize Pomodoro interval data into visual performance charts.',
    status: 'TODO',
    priority: 'LOW',
    category: 'Analytics',
    dueDate: '2026-08-02',
    estimatedMinutes: 60,
  },
];

export const MOCK_GOALS: GoalItem[] = [
  {
    id: 'gl-01',
    title: 'Japan Relocation & JLPT N2 Proficiency',
    description: 'Master Kanji, grammar, and complete visa documentation for Tokyo tech hub relocation.',
    targetMetric: 'JLPT Modules & Visa Prep',
    currentProgress: 65,
    targetValue: 100,
    unit: '%',
    deadline: 'Q4 2026',
    status: 'ON_TRACK',
    category: 'Japan',
    milestones: [
      { id: 'm1', title: 'Complete N3 Kanji Core (1,000 characters)', isCompleted: true },
      { id: 'm2', title: 'Pass JLPT N2 Practice Examination (85%+ score)', isCompleted: true },
      { id: 'm3', title: 'Submit Technical Specialist Visa Documentation', isCompleted: false },
      { id: 'm4', title: 'Secure Software Engineer Offer in Tokyo', isCompleted: false },
    ],
  },
  {
    id: 'gl-02',
    title: 'Zero-Trust Cybersecurity Certification',
    description: 'Achieve CISM & CISSP certifications and zero high-severity vulnerabilities.',
    targetMetric: 'Security Audit Compliance',
    currentProgress: 88,
    targetValue: 100,
    unit: '%',
    deadline: 'Q3 2026',
    status: 'ON_TRACK',
    category: 'Cybersecurity',
    milestones: [
      { id: 'm1', title: 'Implement JWT Refresh Rotation & OAuth 2.0', isCompleted: true },
      { id: 'm2', title: 'Complete Penetration Testing & Vulnerability Audit', isCompleted: true },
      { id: 'm3', title: 'Achieve 100% Security Infrastructure Compliance', isCompleted: false },
    ],
  },
  {
    id: 'gl-03',
    title: 'IELTS Academic Band 8.5 Certification',
    description: 'Master Academic Writing Task 1/2 and Speaking fluency for international standards.',
    targetMetric: 'Practice Test Average Band',
    currentProgress: 80,
    targetValue: 100,
    unit: '%',
    deadline: 'Q4 2026',
    status: 'ON_TRACK',
    category: 'IELTS',
    milestones: [
      { id: 'm1', title: 'Write 30 Academic Essay Prompts', isCompleted: true },
      { id: 'm2', title: 'Achieve Band 8.5 in Listening & Reading Practice', isCompleted: true },
      { id: 'm3', title: 'Conduct Mock Speaking Interviews with Native Speakers', isCompleted: false },
    ],
  },
  {
    id: 'gl-04',
    title: 'SAT Subject Mastery (1550+ Score Target)',
    description: 'Complete Math 800 drill modules and Advanced Evidence-Based Reading.',
    targetMetric: 'Practice Exam Target Score',
    currentProgress: 45,
    targetValue: 100,
    unit: '%',
    deadline: 'Q4 2026',
    status: 'AT_RISK',
    category: 'SAT',
    milestones: [
      { id: 'm1', title: 'Score 800 on College Board Math Practice 1-5', isCompleted: true },
      { id: 'm2', title: 'Complete 50 Reading Comprehension Passage Drills', isCompleted: false },
      { id: 'm3', title: 'Complete Full-Length Timed Diagnostic Exam', isCompleted: false },
    ],
  },
];

export const MOCK_FOCUS_SESSIONS: FocusSession[] = [
  {
    id: 'fs-301',
    title: 'Core Engine Refactoring',
    durationMinutes: 45,
    type: 'DEEP_WORK',
    completedAt: 'Today 11:30 AM',
    productivityRating: 5,
  },
  {
    id: 'fs-302',
    title: 'Security Vulnerability Review',
    durationMinutes: 25,
    type: 'POMODORO',
    completedAt: 'Today 09:15 AM',
    productivityRating: 4,
  },
  {
    id: 'fs-303',
    title: 'System Telemetry Calibration',
    durationMinutes: 25,
    type: 'POMODORO',
    completedAt: 'Yesterday 04:45 PM',
    productivityRating: 5,
  },
];

export const MOCK_JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: 'jnl-501',
    title: 'Architecture Blueprinting & Design Sync',
    content: 'Achieved high clarity on the full-stack architecture. Merged Apple-minimalism with cybersecurity telemetry. **React Query** handles remote state effortlessly.',
    question1: 'Successfully deployed complete authentication flow with JWT refresh rotation.',
    question2: 'Ensuring seamless Tailwind v4 compilation across all dark/light glass panels.',
    question3: 'Implement full-featured task and goals management system.',
    mood: 'OPTIMAL',
    energyLevel: 9,
    tags: ['Architecture', 'React', 'Django', 'Focus'],
    entryDate: '2026-07-22',
    createdAt: '2026-07-22T10:15:00Z',
  },
  {
    id: 'jnl-502',
    title: 'System Telemetry Calibration',
    content: 'Analyzed latency response cycles. Reduced average JWT authorization roundtrip to under 15ms. Maintaining deep focus flow state.',
    question1: 'Tuned PostgreSQL connection pool settings for sub-15ms query execution.',
    question2: 'Mild fatigue during late afternoon deep-work session.',
    question3: 'Refine daily journal three-question prompt workflow.',
    mood: 'FOCUSED',
    energyLevel: 8,
    tags: ['Performance', 'JWT', 'Security'],
    entryDate: '2026-07-21',
    createdAt: '2026-07-21T16:30:00Z',
  },
];

export const MOCK_ANALYTICS_DATA = [
  { day: 'Mon', focusHours: 6.2, tasksDone: 8, efficiency: 88 },
  { day: 'Tue', focusHours: 7.5, tasksDone: 11, efficiency: 94 },
  { day: 'Wed', focusHours: 8.0, tasksDone: 14, efficiency: 97 },
  { day: 'Thu', focusHours: 5.8, tasksDone: 7, efficiency: 82 },
  { day: 'Fri', focusHours: 7.1, tasksDone: 10, efficiency: 91 },
  { day: 'Sat', focusHours: 4.0, tasksDone: 5, efficiency: 85 },
  { day: 'Sun', focusHours: 3.5, tasksDone: 4, efficiency: 90 },
];
