# Generated by Django 4.2.30 on 2026-07-22 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_metric', models.CharField(max_length=150)),
                ('current_progress', models.FloatField(default=0.0)),
                ('target_value', models.FloatField(default=100.0)),
                ('unit', models.CharField(default='%', max_length=50)),
                ('deadline', models.CharField(default='Q3 2026', max_length=50)),
                ('status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('COMPLETED', 'Completed')], default='ON_TRACK', max_length=20)),
                ('category', models.CharField(default='Productivity', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
