# Generated by Django 4.2.30 on 2026-07-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goalitem',
            name='milestones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='goalitem',
            name='category',
            field=models.CharField(default='Cybersecurity', max_length=100),
        ),
        migrations.AlterField(
            model_name='goalitem',
            name='deadline',
            field=models.CharField(default='Q4 2026', max_length=50),
        ),
        migrations.AlterField(
            model_name='goalitem',
            name='target_metric',
            field=models.CharField(default='Target Milestone Progress', max_length=150),
        ),
    ]
