# Generated by Django 4.2.30 on 2026-07-22 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goalitem_description_goalitem_milestones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='goalitem',
            name='category',
            field=models.CharField(db_index=True, default='Cybersecurity', max_length=100),
        ),
        migrations.AlterField(
            model_name='goalitem',
            name='current_progress',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='goalitem',
            name='status',
            field=models.CharField(choices=[('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('COMPLETED', 'Completed')], db_index=True, default='ON_TRACK', max_length=20),
        ),
        migrations.AlterField(
            model_name='goalitem',
            name='target_value',
            field=models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AddIndex(
            model_name='goalitem',
            index=models.Index(fields=['user', 'status'], name='goals_goali_user_id_7ddfbf_idx'),
        ),
        migrations.AddIndex(
            model_name='goalitem',
            index=models.Index(fields=['user', 'category'], name='goals_goali_user_id_251043_idx'),
        ),
    ]
