# Generated by Django 4.2.30 on 2026-07-22 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskitem',
            options={'ordering': ['due_date', '-priority']},
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='category',
            field=models.CharField(db_index=True, default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked')], db_index=True, default='TODO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='taskitem',
            index=models.Index(fields=['user', 'status'], name='tasks_taski_user_id_d627e0_idx'),
        ),
        migrations.AddIndex(
            model_name='taskitem',
            index=models.Index(fields=['user', 'priority'], name='tasks_taski_user_id_6b2f89_idx'),
        ),
        migrations.AddIndex(
            model_name='taskitem',
            index=models.Index(fields=['user', 'due_date'], name='tasks_taski_user_id_ce8d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskitem',
            index=models.Index(fields=['user', 'category'], name='tasks_taski_user_id_613f40_idx'),
        ),
    ]
