# Generated by Django 4.2.30 on 2026-07-22 09:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskitem_options_alter_taskitem_category_and_more'),
        ('focus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='focussession',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AddField(
            model_name='focussession',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='tasks.taskitem'),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='productivity_rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='session_type',
            field=models.CharField(choices=[('POMODORO', 'Pomodoro'), ('DEEP_WORK', 'Deep Work'), ('BREAK', 'Break')], db_index=True, default='POMODORO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['user', 'completed_at'], name='focus_focus_user_id_7e7256_idx'),
        ),
        migrations.AddIndex(
            model_name='focussession',
            index=models.Index(fields=['user', 'session_type'], name='focus_focus_user_id_fd0c65_idx'),
        ),
    ]
