# Generated by Django 4.2.30 on 2026-07-22 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='question_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='question_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='question_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
