# Generated by Django 4.2.30 on 2026-07-22 09:11

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_entry_date_journalentry_question_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-entry_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='energy_level',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('OPTIMAL', 'Optimal'), ('FOCUSED', 'Focused'), ('FATIGUED', 'Fatigued'), ('STRESSED', 'Stressed')], db_index=True, default='FOCUSED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'entry_date'], name='journal_jou_user_id_467e88_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'mood'], name='journal_jou_user_id_8668cb_idx'),
        ),
    ]
