# Generated by Django 4.2.30 on 2026-07-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('user', 'entry_date'), name='unique_user_daily_journal'),
        ),
    ]
