# Generated by Django 4.2.30 on 2026-07-22 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark Cyber Mode'), ('light', 'Apple Light Minimal')], default='dark', max_length=20)),
                ('language', models.CharField(default='en-US', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('email_digest', models.BooleanField(default=True)),
                ('task_reminders', models.BooleanField(default=True)),
                ('focus_alarms', models.BooleanField(default=True)),
                ('private_profile', models.BooleanField(default=True)),
                ('share_telemetry', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Settings',
                'indexes': [models.Index(fields=['user'], name='settings_us_user_id_b56c1e_idx')],
            },
        ),
    ]
